import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Generated from the docs/ folder structure - order controlled by each
  // page's sidebar_position and each category's _category_.json.
  //
  // Published sections need no entry here: the publish tool writes a placeholder
  // page per document and autogeneration picks it up. The underscore-prefixed
  // partials it writes alongside are kept out by the docs plugin's `exclude`, so
  // one document never produces two sidebar entries.
  kbSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
